apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: msterzel/frontend:version3
          ports:
            - containerPort: 3000
              name: "http"
          env:
            - name: RECOMMENDATION_HOST
              value: $(MOVIE_RECOMMENDATION_SERVICE_SERVICE_HOST)
            - name: BASE_HOST
              value: $(MOVIE_BASE_SERVICE_SERVICE_HOST)
            - name: USER_HOST
              value: $(USER_SERVICE_SERVICE_SERVICE_HOST)
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
