{
 "title": "Usage | Movie Recommendation Application",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Server Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_max{application=\"Movie Recommendation Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Movie Base Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"localhost:8084\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"localhost:8084\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  { "title": "Movie Recommendation Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"localhost:8082\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  { "title": "User Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"localhost:8081\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"localhost:8081\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}