apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
spec:
  type: NodePort
  selector:
    app: mysql-db
  ports:
    - name: "mysql"
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306