apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-persisent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: mysql-data-persisent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/gracz/k8s"