apiVersion: v1
kind: Service
metadata:
  name: movie-base-service
spec:
  type: NodePort
  selector:
    app: movie-base
  ports:
    - name: "http"
      protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084