apiVersion: v1
kind: Service
metadata:
  name: movie-recommendation-service
spec:
  type: NodePort
  selector:
    app: movie-recommendation
  ports:
    - name: "http"
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082