apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - name: "http"
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081